[env]
# RUST_BACKTRACE = "1" # 堆栈跟踪

[build]
# jobs = 4 # 编译时核心数

# for Windows 
# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"
# ar = "x86_64-w64-mingw32-gcc-ar"

# for Linux
# [target.x86_64-unknown-linux-musl]
# linker = "x86_64-linux-musl-gcc"
